### ISSUE TITLE
OAuth

### ISSUE THREAD

**Issue by tmerlier** [etalab/cartes.data.gouv.fr#2]
Adding a new backend

**Comment by yohanboniface** [comment]
Doc on how to create a new Oauth connector: http://psa.matiasaguirre.net/docs/backends/implementation.html

Example of data.gouv.fr Oauth consuming: https://github.com/etalab/collectivites.data.gouv.fr/blob/master/collectivites/views.py#L67 (not Django, but you got the fields)

We'll need a new client in data.gouv.fr for that, I'll deal with @noirbizarre for that :)
