### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by tmerlier** [etalab/cartes.data.gouv.fr#6]

**Comment by davidbgk** [comment]
License, perenniality, availability and so on.

**Comment by davidbgk** [comment]
<img width="1242" alt="capture d ecran 2017-04-26 a 18 18 01" src="https://cloud.githubusercontent.com/assets/3556/25459539/bdcb14ca-2aac-11e7-88e4-380196509919.png">

What about *no* about page? /cc @yohanboniface

**Comment by yohanboniface** [comment]
I'd better keep the home page free of those informations, but let's discuss :)
And now let's go to fly!
